name: lact-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: 40

modules:
  - from-file: packages.yml
  - from-file: display-manager.yml
  - from-file: services.yml
  - type: files
    files:
      - usr: /usr
  - type: script
    scripts: modify-os-release.sh

  - type: signing
